### PR TITLE
Add precise Atan and Acos functions

### PR DESCRIPTION
**Pull request by sam-vdp**
I noticed the Atan2 function is using a linear approximation. This PR adds Atan and Acos using a Euler series, which is more precise (and a lot slower of course).

### CODE REVIEW

**Comment by sam-vdp** [comment]
This will probably need a good amount of code review and fixing, please feel free to reject this if necessary.
I think a small comment for the existing Atan mentioning the limitations would be helpful though.

**Comment by asik** [comment]
I'll look at it, sorry if it's taking time. A lot of what I mentioned in the other PR might also apply here so you could pre-emptively address that.

**Comment by asik** [comment]
LGTM except a few things I'll fix after. Please rebase and fix merge conflicts and I'll merge.

**Comment by sam-vdp** [comment]
Done

**Comment by asik** [comment]
Thank you for this contribution!

**Pull request merged**
